"""
market_summary_service.py

Builds the structured prompt sent to AI providers for market summaries.
Includes a mandatory disclaimer in the prompt itself so every AI response
contains it regardless of which model is used.
"""

from __future__ import annotations


DISCLAIMER = (
    '\n\n---\n'
    '⚠️  DISCLAIMER: This analysis is generated by an AI model for '
    'research and educational purposes ONLY. It does NOT constitute '
    'financial advice, investment recommendations, or solicitation to '
    'buy or sell any security. Always consult a licensed financial '
    'advisor before making investment decisions. Past performance does '
    'not guarantee future results.\n'
    '---\n'
)


def build_market_summary_prompt(
    scan_results: list[dict],
    news_by_ticker: dict[str, list[dict]],
    universe_id: str | None,
) -> str:
    """
    Build a structured research prompt from scan results and news.

    Args:
        scan_results:    List of stock dicts from the scanner (sorted by score desc).
        news_by_ticker:  Dict mapping ticker → list of news article dicts.
        universe_id:     Universe label (e.g. 'sp500').

    Returns:
        A formatted prompt string ready to be sent to an AI provider.
    """
    universe_label = universe_id or 'custom watchlist'
    total = len(scan_results)

    lines = [
        f'# AI Market Summary — Universe: {universe_label.upper()} ({total} stocks scanned)',
        '',
        'You are analyzing a quantitative stock scan. Provide a concise '
        'executive summary, highlight the most interesting setups, identify '
        'any notable news catalysts, and flag key risks. Do NOT make '
        'buy/sell/hold recommendations.',
        DISCLAIMER,
        '## Top 10 Stocks by Score',
        '',
    ]

    top10 = sorted(scan_results, key=lambda x: x.get('score', 0), reverse=True)[:10]
    for r in top10:
        ticker = r.get('ticker', '?')
        lines.append(
            f"- **{ticker}** | Score: {r.get('score', 0):.1f} | "
            f"Price: ${r.get('price', 0):.2f} | "
            f"RSI: {r.get('rsi', 0):.1f} | "
            f"Vol Ratio: {r.get('volume_ratio', 0):.2f}x | "
            f"RS vs SPY (20d): {_pct(r.get('relative_strength_20d'))} | "
            f"MA Spread: {_pct(r.get('ma_spread_percent'))} | "
            f"Signals: {', '.join(r.get('categories', [])) or 'none'}"
        )

    lines += ['', '## Category Breakdown', '']
    categories: dict[str, list[str]] = {}
    for r in scan_results:
        for cat in r.get('categories', []):
            categories.setdefault(cat, []).append(r.get('ticker', '?'))

    for cat, tickers in sorted(categories.items(), key=lambda x: -len(x[1])):
        lines.append(f'- **{cat}** ({len(tickers)}): {", ".join(tickers[:15])}')

    # News
    if news_by_ticker:
        lines += ['', '## Recent News Headlines', '']
        for ticker in list(news_by_ticker.keys())[:10]:
            articles = news_by_ticker[ticker]
            if not articles:
                continue
            lines.append(f'**{ticker}**:')
            for art in articles[:3]:
                title = art.get('title', '(no title)')
                pub = art.get('publisher', '')
                lines.append(f'  - {title}  [{pub}]')

    lines += [
        '',
        '## Market Stats',
        f'- Total stocks scanned: {total}',
        f'- Bullish signals: {sum(1 for r in scan_results if r.get("score", 0) >= 60)}',
        f'- Bearish signals: {sum(1 for r in scan_results if r.get("score", 0) <= 30)}',
        '',
        'Please provide:',
        '1. A 2–3 sentence executive summary of overall market tone.',
        '2. Top 3 most interesting stock setups and why.',
        '3. Any notable sector themes or macro patterns.',
        '4. Key risks to watch.',
        DISCLAIMER,
    ]

    return '\n'.join(lines)


def _pct(value) -> str:
    if value is None:
        return 'N/A'
    try:
        return f'{float(value):+.1f}%'
    except (TypeError, ValueError):
        return 'N/A'
